### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by mnpenner** [papandreou/node-pngquant#6]
I'm having trouble installing this on FreeBSD. Output is:

```
$ npm i pngquant
npm WARN package.json herbert@0.1.0 No README data
|
> pngquant-bin@3.0.0 postinstall /usr/local/herbert/node_modules/pngquant/node_modules/pngquant-bin
> node lib/install.js

  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at ChildProcess.exithandler (child_process.js:214:12)
    at emitTwo (events.js:88:13)
    at ChildProcess.emit (events.js:173:7)
    at maybeClose (internal/child_process.js:819:16)
    at Socket.<anonymous> (internal/child_process.js:320:11)
    at emitOne (events.js:78:13)
    at Socket.emit (events.js:170:7)
    at Pipe._onclose (net.js:470:12)
pngquant@0.6.0 node_modules/pngquant
├── which@1.1.2 (is-absolute@0.1.7)
├── memoizeasync@0.8.0 (passerror@0.0.2, lru-cache@2.5.0)
└── pngquant-bin@3.0.0 (logalot@2.1.0, bin-build@2.2.0, bin-wrapper@3.0.2)
```

I already have the `graphics/png` package installed. Is there something else I need, or some way I can make this work?

**Comment by papandreou** [comment]
Should be raised with https://github.com/imagemin/pngquant-bin#readme if it's still an issue.
