### ISSUE TITLE
GLIBC_2.14 not found on CentOS 6.6

### ISSUE THREAD

**Issue by magic890** [papandreou/node-pngquant#7]
Running `pngquant()` trigger this error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: /usr/share/nginx/html/myproject/node_modules/pngquant-bin/vendor/pngquant: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/nginx/html/myproject/node_modules/pngquant-bin/vendor/pngquant)

    at Socket.<anonymous> (/usr/share/nginx/html/myproject/node_modules/imagemin-pngquant/index.js:62:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

OS: CentOS release 6.6 (Final)
Kernel: 2.6.32-431.23.3.el6.x86_64 GNU/Linux

**Comment by rauluranga** [comment]
this could be related:

[Node.js Imagemin on Centos](http://stackoverflow.com/questions/29930978/node-js-imagemin-on-centos)

> This error means that the system is lacking libpng development library, which is needed to install imagemin Node.JS module. To install it on CentOS 6, you need to issue this command: yum install libpng-devel

**Comment by papandreou** [comment]
It's probably an issue with [`pngquant-bin`](https://github.com/imagemin/pngquant-bin), but maybe we could catch that error and try to fall back to the system-wide install.
